# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79df4fd4d71673e12018db3529d1ae3c6e5afad26d333fcaa10fe3f6a70e35c63655fa0ca22e122faaa652b886776cc89eecc40844260f5bc72d02d56b1fe8ce

test:
  secret_key_base: 6c663e6da29aea74e16ed384d0c3fed3669342bbcd555b9c6139b85e24ff2177aa9d6a3fbbb688ebf60f888512c7b29dc97b0cb7cfa8acfa17c4b12150022f05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
